# Generated by Django 5.1.3 on 2024-11-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='text',
        ),
    ]
