# Generated by Django 5.1.3 on 2024-11-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_user_alter_doctor_user'),
        ('subscriptions', '0003_alter_plan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='name',
            new_name='plan_offer',
        ),
        migrations.AddField(
            model_name='plan',
            name='hospital',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='hospital.hospital'),
            preserve_default=False,
        ),
    ]
