# Generated by Django 5.1.3 on 2024-11-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_role_user_user_type_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hospital',
            field=models.BooleanField(default=False),
        ),
    ]
