# Generated by Django 5.1.3 on 2024-11-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital_admin', 'Hospital Admin'), ('superuser', 'Superuser')], default=3),
        ),
    ]
