# Generated by Django 5.1.3 on 2024-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_type_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('hospital_admin', 'Hospital Admin'), ('superuser', 'Superuser')], default='patient', max_length=50),
        ),
    ]
